### ISSUE TITLE
Incompatibility with More Right Click Functions

### ISSUE THREAD

**Issue by ghost** [manyrandomthings/minitweaks#29]
Hello, this is the crash report: https://pastebin.com/raw/05kd8nbj
This is the mod: https://github.com/willatendo/More-Right-Click-Functions

Thanks already! 😊

**Comment by manyrandomthings** [comment]
Their mod is overwriting the shovel use method instead of using something like `@Inject` so it can't be fixed from my side.

https://github.com/willatendo/More-Right-Click-Functions/blob/1687dafb09e8b331d1174905ee65fbb024e3e1c6/src/main/java/morerightclickfunctions/mixin/GrindablesAdderMixin.java#L29-L49

**Comment by ghost** [comment]
Thank you for the fast response.
